### ISSUE TITLE
Local Environment Setup Clarification

### ISSUE THREAD

**Issue by moviedatascience** [LambdaSchool/Labs-Sprint-Challenge-1.4-Delivery#1]
## Currently Reads:

> Local environment: Elaborate on your local environment set up. What problems came up during your local development environment set up? How did you overcome them?

## Potential Issue:

DS students don't have an isolated environment that they setup for a particular project. Depending on the scope of the project, many will just work within the base python environment that they installed most of their packages on. 

## Potential Solution:

While some work in base, most students will at least create a pipenv where they install dependencies. Asking leading questions for DS students to clarify what is meant by local environment may be helpful. 

> Local environments for DS students could mean: pipenv, virtualenv, docker, or k8 clusters. How have you utilized tools to ensure reproducibility when your product is deployed? How do packages and dependencies get loaded into your hosted environment?

**Comment by ryan-hamblin** [comment]
I added this right into the prompt thanks again.
