### ISSUE TITLE
Pull Requests for DS 

### ISSUE THREAD

**Issue by moviedatascience** [LambdaSchool/Labs-Sprint-Challenge-1.4-Delivery#2]
## Currently Reads:

> Pull requests: Show us a piece of your code that you're proud of. Provide a link to a pull request that you're proud of.

## Potential Issue:

I know that my team never used pull requests when collaborating in GH. We are taught in the curriculum to just fork the repo and push changes to master. 

Additionally, depending on the setup of the team, you may have some DS team members that just don't work on code for GH at all. I have a two member DS team and one exclusively works on the Data Engineering side with things like DB configuration, deploying endpoints, and optimizing SQL queries. 

## Potential Solution:

I would just add a disclaimer to DS students that if they don't have pull requests that they have made they should include commits they made to the repo. Something like:

> For DS Students: if you haven't made a pull request, provide a link to the commits you have made to the repo. If you have not been working on code directly, expand on what other aspects of the project you have focused on.

**Comment by ryan-hamblin** [comment]
I love this so much. Thanks Eric.
